"""Generate a standalone Manim .py file from a storyboard."""

from pathlib import Path
from vidgen.schema import Storyboard
from vidgen.social import FORMATS, PACING, SOCIAL_FONTS

# Template type → module name mapping
TEMPLATE_MAP = {
    "hook": "hook",
    "title": "title",
    "bullet_list": "bullet_list",
    "two_panel": "two_panel",
    "comparison_table": "comparison_table",
    "flowchart": "flowchart",
    "bar_chart": "bar_chart",
    "scatter_plot": "scatter_plot",
    "pipeline_diagram": "pipeline_diagram",
    "equation": "equation",
    "closing": "closing",
}


def generate(storyboard: Storyboard, output_path: Path) -> list[str]:
    """
    Generate a .py file with one Scene class per storyboard scene.
    Returns list of class names in order.
    """
    lines = []
    class_names = []

    # Resolve format profile
    fmt_name = storyboard.meta.format
    fmt = FORMATS.get(fmt_name, FORMATS["presentation"])

    # Resolve pacing
    pacing_name = storyboard.meta.pacing or fmt.pacing
    timing = PACING.get(pacing_name, PACING["slow"])
    fonts = SOCIAL_FONTS.get(pacing_name, SOCIAL_FONTS["slow"])

    # Use format's resolution
    width = fmt.width
    height = fmt.height

    # Header
    lines.append("# Auto-generated by vidgen — do not edit manually")
    lines.append("import sys, os")
    lines.append("sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))")
    lines.append("from manim import *")
    lines.append("import numpy as np")
    lines.append("")
    lines.append("from vidgen.config import set_theme, COLORS, TIMING, FONTS")
    lines.append(f"set_theme({storyboard.meta.color_theme!r})")
    lines.append("")
    lines.append("# Override timing and fonts for format")
    lines.append(f"TIMING.update({timing!r})")
    lines.append(f"FONTS.update({fonts!r})")
    lines.append("")
    lines.append("# Manim config")
    lines.append(f"config.pixel_height = {height}")
    lines.append(f"config.pixel_width = {width}")
    lines.append(f"config.frame_height = {fmt.frame_height}")
    lines.append(f"config.frame_width = {fmt.frame_width}")
    lines.append('config.movie_file_extension = ".webm"')
    lines.append('config.background_color = COLORS["bg_main"]')
    lines.append("")

    # Import all template modules
    imported = set()
    for scene in storyboard.scenes:
        tpl = TEMPLATE_MAP[scene.type]
        if tpl not in imported:
            lines.append(f"from vidgen.templates import {tpl} as tpl_{tpl}")
            imported.add(tpl)
    lines.append("")

    # Generate scene classes
    for i, scene in enumerate(storyboard.scenes):
        class_name = f"S{i:02d}_{scene.id}"
        class_names.append(class_name)
        tpl = TEMPLATE_MAP[scene.type]

        # Serialize scene data as dict literal, inject timing
        scene_dict = scene.model_dump()
        scene_dict["timing"] = timing
        scene_dict["font_size"] = fonts.get("hook_text", 52)

        lines.append(f"class {class_name}(Scene):")
        lines.append(f"    def construct(self):")
        lines.append(f"        data = {scene_dict!r}")
        lines.append(f"        tpl_{tpl}.render(self, data)")
        lines.append("")

    output_path.write_text("\n".join(lines))
    return class_names
